/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Dom: typeof import('./utils/dom.ts')['default']
    File: typeof import('./utils/file.ts')['default']
    Gettext: typeof import('./utils/gettext.ts')['default']
    Invoke: typeof import('./utils/invoke.ts')['default']
    Langs: typeof import('./utils/langs.ts')['default']
    LocaleCreator: typeof import('./components/LocaleCreator.vue')['default']
    NConfigProvider: typeof import('naive-ui')['NConfigProvider']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
